= Project: {IOT_1}

=== Author: azmm12.
=== Email: {Abdulazizmmutiri@gmail.com} .
=== Date: 20/07/2022 .
=== Revision: version#1 .
=== License: Public Domain .

== Description of project:
Designing Web Audio Speech Recognition using javascript.

== Installation Steps:
1. Visual Studio Code or Open Online Javascript Compiler .
2. Download P5.speech libraries .
3. Design simple front page .
4. Write Code for Javascript to convert Audio to speech in Arabic .
5. Upload Javascript code to Compiler and Simulate it .

=== Folder structure

....
 First_Task_IOT
  ├── sketch.js       => javascript file
  ├── libraries      => javascript library files
  ├── index.html     => HTML file
  ├── style.css  => CSS file
  └── ReadMe.adoc      => this file
....

=== Contributing
To contribute to this project please contact azmm12 https://id.arduino.cc/azmm12

=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
